version: '3.2'

services:
 elasticsearch:
   build:
     context: elasticsearch/
   volumes:
     - elasticsearch:/usr/share/elasticsearch/data
     - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
     ELASTIC_PASSWORD: password
     discovery.type: single-node
   networks:
     - elk_stack

 logstash:
   build:
     context: logstash/
   ports:
     - "5000:5000"
     - "9600:9600"
   environment:
     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
   volumes:
     - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
     - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
     - ~/Downloads/elk-logs/:/usr/share/logstash/elk-logs/:ro
   networks:
     - elk_stack
   depends_on:
     - elasticsearch

 kibana:
   build:
     context: kibana/
   ports:
     - "5601:5601"
   volumes:
     - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
   networks:
     - elk_stack
   depends_on:
     - elasticsearch

networks:
 elk_stack:
   driver: bridge

volumes:
 elasticsearch: