version: '3'
services:

  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    command: --copy-service # seemingly required to load directory.ldif
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_ADMIN_PASSWORD=password
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_PASSWORD=password
    volumes:
      - ./ldif/directory.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/directory.ldif
    networks:
      - ldap-net

  openldap-admin:
    image: osixia/phpldapadmin:0.9.0
    container_name: openldap-admin
    ports:
      - 6443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    networks:
      - ldap-net

networks:
  ldap-net:
